services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petstoreportal

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@petstore.com
      PGADMIN_DEFAULT_PASSWORD: Password

    ports:
      - "4321:80"

  redis:
    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend/pet-adoption-portal

    container_name: pet-adoption-backend

    depends_on:
      - postgres

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petstoreportal
      DB_USERNAME: admin
      DB_PASSWORD: password

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: pet-adoption-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres_data: