services:

  postgres:
    image: postgres:17
    container_name: pet-adoption-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petstoreportal

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d petstoreportal"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pet-adoption-pgadmin

    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@petstore.com
      PGADMIN_DEFAULT_PASSWORD: Password

    ports:
      - "4321:80"


  backend:
    build:
      context: ./backend/pet-adoption-portal
      dockerfile: Dockerfile

    container_name: pet-adoption-backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petstoreportal
      DB_USERNAME: admin
      DB_PASSWORD: password

      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/pet-adoption-portal
      dockerfile: Dockerfile

    container_name: pet-adoption-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

    restart: unless-stopped

volumes:
  postgres_data: