CREATE SEQUENCE pets_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE pets
(
    id BIGINT NOT NULL DEFAULT nextval('pets_seq'),
    tag VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    species VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    intake_date DATE NOT NULL,
    breed VARCHAR(255),
    gender VARCHAR(255),
    status VARCHAR(255),
    weight DOUBLE PRECISION,
    color VARCHAR(20),
    description VARCHAR(200),
    image_url VARCHAR(255),
    is_vaccinated BOOLEAN,
    is_neutered BOOLEAN,
    CONSTRAINT pets_pkey PRIMARY KEY (id),
    CONSTRAINT pets_gender_check CHECK (gender IN (
                       'MALE',
                       'FEMALE',
                       'UNKNOWN'
                )
            ),

    CONSTRAINT pets_species_check CHECK (species IN (
                        'CAT',
                        'DOG',
                        'BIRD',
                        'FISH',
                        'RABBIT',
                        'GUINEA_PIG',
                        'HAMSTER',
                        'REPTILE',
                        'AMPHIBIAN',
                        'INSECT'
                )
            ),

    CONSTRAINT pets_status_check CHECK (status IN (
                       'UNAVAILABLE',
                       'AVAILABLE',
                       'PENDING_ADOPTION',
                       'ADOPTED'
                )
            )
);

CREATE TABLE adoption_requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    applicant_id BIGINT NOT NULL,
    status VARCHAR(255),
    requested_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT adoption_requests_status_check CHECK (status IN (
                       'PENDING',
                       'CHECKIN',
                       'PAYMENT_PENDING',
                       'APPROVED',
                       'REJECTED'
                )
            )
);

ALTER TABLE adoption_requests
    ADD CONSTRAINT fk_adoption_request_pet
        FOREIGN KEY (pet_id)
            REFERENCES pets (id);

ALTER TABLE adoption_requests
    ADD CONSTRAINT fk_adoption_request_user
        FOREIGN KEY (applicant_id)
            REFERENCES users (id);