SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3459 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16504)
-- Name: adoption_requests; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.adoption_requests (
    applicant_id bigint NOT NULL,
    id bigint NOT NULL,
    pet_id bigint NOT NULL,
    requested_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(255),
    CONSTRAINT adoption_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CHECKIN'::character varying, 'PAYMENT_PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.adoption_requests OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16503)
-- Name: adoption_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.adoption_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adoption_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16431)
-- Name: adoption_requests_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.adoption_requests_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.adoption_requests_seq OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 16510)
-- Name: pets; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.pets (
    age integer NOT NULL,
    intake_date date NOT NULL,
    is_neutered boolean,
    is_vaccinated boolean,
    weight double precision,
    id bigint NOT NULL,
    color character varying(20),
    name character varying(100) NOT NULL,
    description character varying(200),
    breed character varying(255),
    gender character varying(255),
    image_url character varying(255),
    species character varying(255) NOT NULL,
    status character varying(255),
    tag character varying(255) NOT NULL,
    CONSTRAINT pets_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT pets_species_check CHECK (((species)::text = ANY ((ARRAY['CAT'::character varying, 'DOG'::character varying, 'BIRD'::character varying, 'FISH'::character varying, 'RABBIT'::character varying, 'GUINEA_PIG'::character varying, 'HAMSTER'::character varying, 'REPTILE'::character varying, 'AMPHIBIAN'::character varying, 'INSECT'::character varying])::text[]))),
    CONSTRAINT pets_status_check CHECK (((status)::text = ANY ((ARRAY['UNAVAILABLE'::character varying, 'AVAILABLE'::character varying, 'PENDING_ADOPTION'::character varying, 'ADOPTED'::character varying])::text[])))
);


ALTER TABLE public.pets OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 16502)
-- Name: pets_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.pets_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pets_seq OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 16523)
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 16522)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3450 (class 0 OID 16504)
-- Dependencies: 220
-- Data for Name: adoption_requests; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.adoption_requests (applicant_id, id, pet_id, requested_at, updated_at, status) FROM stdin;
\.


--
-- TOC entry 3451 (class 0 OID 16510)
-- Dependencies: 221
-- Data for Name: pets; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.pets (age, intake_date, is_neutered, is_vaccinated, weight, id, color, name, description, breed, gender, image_url, species, status, tag) FROM stdin;
10	2026-08-21	f	f	1000	1	\N	Fawkes	Loyal, can carry immense loads, bursts into flames and gets reborn again	Phoenix	UNKNOWN	https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/The_Making_of_Harry_Potter_29-05-2012_%28Fawkes%29.jpg/960px-The_Making_of_Harry_Potter_29-05-2012_%28Fawkes%29.jpg	BIRD	AVAILABLE	BRD-2026-00001
20	2026-08-21	f	f	100	2	\N	Nagini	She was a witch, now she is a snake. Very useful Horcrux	Meledictus	UNKNOWN	https://i.redd.it/4yfh6tw8ltyc1.jpeg	REPTILE	AVAILABLE	REP-2026-00002
1000	2026-08-21	f	f	1000	3	\N	Basilisk	Monster in the Chamber of Secrets. Controlled on by true Heir of Slytherin	Basilisk	UNKNOWN	https://monsterlegacy.net/wp-content/uploads/2013/03/basiliskfinalresize.jpg	REPTILE	AVAILABLE	REP-2026-00003
10	2026-08-21	f	f	5	4	\N	Hedwig	Trustee mail carrier.	White Owl	UNKNOWN	https://cdn.europosters.eu/image/750/149370.jpg	BIRD	AVAILABLE	BRD-2026-00004
2	2026-08-21	f	f	70	5	\N	Scabbers	Peter Pettigrew. Missing one toe.	Animagus	UNKNOWN	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgF90vFW_rN_R1vVVzu18XI1bgkNYIuSJ2T3i6Slis3m9bMzzwcywMKIs&s=10	GUINEA_PIG	AVAILABLE	GPG-2026-00005
15	2026-08-21	t	t	30	6	\N	Padfoot	Sirius Black. Best friend of James Potter. Godfather of the Chosen One.	Animagus	UNKNOWN	https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2018/09/1200/675/padfoot.jpg?ve=1&tl=1	DOG	AVAILABLE	DOG-2026-00006
30	2026-08-21	t	t	30	7	\N	Moony	Remus Lupin. Got bit when he was young	Werewolf	UNKNOWN	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZnG82Zu_DmIJOgqk3ESSZrf79BDP2g20c-k3s7dO7gdDFXQPj3Ir7zdI&s=10	DOGAVAILABLE	DOG-2026-00007
15	2026-08-21	f	f	30	8	\N	Wormtail	Same as Peter Pettigrew.	Animagus	UNKNOWN	https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg	GUINEA_PIG	AVAILABLE	GPG-2026-00008
1000	2026-08-21	t	t	200	9	\N	Fluffy	Hagrid's pet. Gave to Dumbledore for protection. Sleeps when music plays.	Three-headed Dog	UNKNOWN	https://contentful.harrypotter.com/usf1vwtuqyxm/3tc7hPhyNomfJ5Ez1j398n/70624368dc7f0d19605d35a7783fdc22/fluffy-hp-f1-fact-file-hero.jpg	DOG	AVAILABLE	DOG-2026-00009
100	2026-08-21	f	f	40	10	\N	Aragog	Hagrid's  pet. Rescued from the Forbidden forest.	Acromantual	UNKNOWN	https://monsterlegacy.net/wp-content/uploads/2017/02/aragogbeauty.jpg	INSECT	AVAILABLE	INS-2026-00010
1000	2026-08-21	f	f	10000	11	\N	Fenrir	\N		UNKNOWN	https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg	DOG	AVAILABLE	DOG-2026-00011
1000	2026-08-21	f	f	10000	12	\N	Fenrir	\N		UNKNOWN	https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg	DOG	AVAILABLE	DOG-2026-00012
\.


--
-- TOC entry 3453 (class 0 OID 16523)
-- Dependencies: 223
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, email, full_name, password_hash, role) FROM stdin;
1	admin.one@petstore.com	Admin One	$2a$10$7vekC6K2mDMHOVSKRVeAkeL5kFp1/iwGRMELrWeWzIZhOb4PmlSFG	ADMIN
\.


--
-- TOC entry 3460 (class 0 OID 0)
-- Dependencies: 219
-- Name: adoption_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.adoption_requests_id_seq', 1, false);


--
-- TOC entry 3461 (class 0 OID 0)
-- Dependencies: 217
-- Name: adoption_requests_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.adoption_requests_seq', 1, false);


--
-- TOC entry 3462 (class 0 OID 0)
-- Dependencies: 218
-- Name: pets_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.pets_seq', 1, false);


--
-- TOC entry 3463 (class 0 OID 0)
-- Dependencies: 222
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3291 (class 2606 OID 16509)
-- Name: adoption_requests adoption_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.adoption_requests
    ADD CONSTRAINT adoption_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 3293 (class 2606 OID 16519)
-- Name: pets pets_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT pets_pkey PRIMARY KEY (id);


--
-- TOC entry 3295 (class 2606 OID 16521)
-- Name: pets pets_tag_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT pets_tag_key UNIQUE (tag);


--
-- TOC entry 3297 (class 2606 OID 16532)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3299 (class 2606 OID 16530)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 16533)
-- Name: adoption_requests fkfiquo1yi2fy13fw43bvycbn2l; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.adoption_requests
    ADD CONSTRAINT fkfiquo1yi2fy13fw43bvycbn2l FOREIGN KEY (applicant_id) REFERENCES public.users(id);


--
-- TOC entry 3301 (class 2606 OID 16538)
-- Name: adoption_requests fknbrvxfu9ncpliue6x29ohsyno; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.adoption_requests
    ADD CONSTRAINT fknbrvxfu9ncpliue6x29ohsyno FOREIGN KEY (pet_id) REFERENCES public.pets(id);


