services:
  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=petstoreportal

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=archisman.chakraborty@npstx.com
      - PGADMIN_DEFAULT_PASSWORD=Password@2nd

    ports:
      - "4321:80"

  redis:
    image: redis:7
    container_name: redis

    ports:
      - "6379:6379"

volumes:
  postgres_data:
       
