spring.application.name=pet-adoption-portal

# spring.datasource.url=jdbc:postgresql://localhost:5432/petstoreportal
# spring.datasource.username=admin
# spring.datasource.password=password

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# base path
server.servlet.context-path=/api

# JWT configuration
jwt.secret=Jb4TZ3tJDKCNJyqjZ/ATeRricvaVoNRBY+z1zAJY6g4=
# 1 hour expiration
jwt.expiration=3600000