

INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (1, 1000, 'Phoenix', NULL, 'Loyal, can carry immense loads, bursts into flames and gets reborn again', 'UNKNOWN', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/The_Making_of_Harry_Potter_29-05-2012_%28Fawkes%29.jpg/960px-The_Making_of_Harry_Potter_29-05-2012_%28Fawkes%29.jpg', '2026-08-21', 'Fawkes', false, 'BIRD', 'AVAILABLE', 'BRD-2026-00001', false, 10);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (2, 100, 'Meledictus', NULL, 'She was a witch, now she is a snake. Very useful Horcrux', 'UNKNOWN', 'https://i.redd.it/4yfh6tw8ltyc1.jpeg', '2026-08-21', 'Nagini', false, 'REPTILE', 'AVAILABLE', 'REP-2026-00002', false, 20);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (3, 1000, 'Basilisk', NULL, 'Monster in the Chamber of Secrets. Controlled on by true Heir of Slytherin', 'UNKNOWN', 'https://monsterlegacy.net/wp-content/uploads/2013/03/basiliskfinalresize.jpg', '2026-08-21', 'Basilisk', false, 'REPTILE', 'AVAILABLE', 'REP-2026-00003', false, 1000);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (4, 5, 'White Owl', NULL, 'Trustee mail carrier.', 'UNKNOWN', 'https://cdn.europosters.eu/image/750/149370.jpg', '2026-08-21', 'Hedwig', false, 'BIRD', 'AVAILABLE', 'BRD-2026-00004', false, 10);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (5, 70, 'Animagus', NULL, 'Peter Pettigrew. Missing one toe.', 'UNKNOWN', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgF90vFW_rN_R1vVVzu18XI1bgkNYIuSJ2T3i6Slis3m9bMzzwcywMKIs&s=10', '2026-08-21', 'Scabbers', false, 'GUINEA_PIG', 'AVAILABLE', 'GPG-2026-00005', false, 2);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (6, 30, 'Animagus', NULL, 'Sirius Black. Best friend of James Potter. Godfather of the Chosen One.', 'UNKNOWN', 'https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2018/09/1200/675/padfoot.jpg?ve=1&tl=1', '2026-08-21', 'Padfoot', true, 'DOG', 'AVAILABLE', 'DOG-2026-00006', true, 15);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (7, 30, 'Werewolf', NULL, 'Remus Lupin. Got bit when he was young', 'UNKNOWN', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZnG82Zu_DmIJOgqk3ESSZrf79BDP2g20c-k3s7dO7gdDFXQPj3Ir7zdI&s=10', '2026-08-21', 'Moony', true, 'DOG', 'AVAILABLE', 'DOG-2026-00007', true, 30);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (8, 30, 'Animagus', NULL, 'Same as Peter Pettigrew.', 'UNKNOWN', 'https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg', '2026-08-21', 'Wormtail', false, 'GUINEA_PIG', 'AVAILABLE', 'GPG-2026-00008', false, 15);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (9, 200, 'Three-headed Dog', NULL, 'Hagrid''s pet. Gave to Dumbledore for protection. Sleeps when music plays.', 'UNKNOWN', 'https://contentful.harrypotter.com/usf1vwtuqyxm/3tc7hPhyNomfJ5Ez1j398n/70624368dc7f0d19605d35a7783fdc22/fluffy-hp-f1-fact-file-hero.jpg', '2026-08-21', 'Fluffy', true, 'DOG', 'AVAILABLE', 'DOG-2026-00009', true, 1000);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (10, 40, 'Acromantual', NULL, 'Hagrid''s  pet. Rescued from the Forbidden forest.', 'UNKNOWN', 'https://monsterlegacy.net/wp-content/uploads/2017/02/aragogbeauty.jpg', '2026-08-21', 'Aragog', false, 'INSECT', 'AVAILABLE', 'INS-2026-00010', false, 100);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (11, 10000, '', NULL, NULL, 'UNKNOWN', 'https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg', '2026-08-21', 'Fenrir', false, 'DOG', 'AVAILABLE', 'DOG-2026-00011', false, 1000);
INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age) VALUES (12, 10000, '', NULL, NULL, 'UNKNOWN', 'https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg', '2026-08-21', 'Fenrir', false, 'DOG', 'AVAILABLE', 'DOG-2026-00012', false, 1000);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO users(id, email, full_name, password_hash, role) VALUES (1, 'admin.one@petstore.com', 'Admin One', '$2a$10$7vekC6K2mDMHOVSKRVeAkeL5kFp1/iwGRMELrWeWzIZhOb4PmlSFG', 'ADMIN');


-- INSERT INTO pets(id, weight, breed, color, description, gender, image_url, intake_date, name, is_neutered, species, status, tag, is_vaccinated, age)